# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "sosi-veileder-i-standardisering"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "standardisering"
